//
//  math.h
//  GRPH stdlib - libgrph
//
//  Autogenerated by `grph gen-header math`.
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

#ifndef GRPH_NS_MATH_H
#define GRPH_NS_MATH_H

#include "grph_types.h"

grph_float_t grph_math_PI(void);

#endif /* GRPH_NS_MATH_H */

