//
//  math.h
//  GRPH stdlib - libgrph
//
//  Autogenerated by `grph gen-header math`.
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

#ifndef GRPH_NS_MATH_H
#define GRPH_NS_MATH_H

#include "grph_types.h"
#include "grph_shapes.h"

grph_float_t grph_math_sqrt(struct grph_existential * number);
grph_float_t grph_math_cbrt(struct grph_existential * number);
grph_float_t grph_math_pow(struct grph_existential * number, struct grph_existential * power);
grph_float_t grph_math_PI(void);
grph_integer_t grph_math_round(struct grph_existential * number);
grph_integer_t grph_math_floor(struct grph_existential * number);
grph_integer_t grph_math_ceil(struct grph_existential * number);

#endif /* GRPH_NS_MATH_H */

