//
//  stdio.h
//  GRPH stdlib - libgrph
//
//  Autogenerated by `grph gen-header stdio`.
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

#ifndef GRPH_NS_STDIO_H
#define GRPH_NS_STDIO_H

#include "grph_types.h"

grph_string_t grph_stdio_getLineInString(grph_string_t string, grph_integer_t line);
grph_integer_t grph_stdio_getTimeInMillisSinceLoad();
grph_string_t grph_stdio_getSVGFromCurrentImage();
void grph_stdio_printOut(grph_string_t message);
void grph_stdio_printError(grph_string_t message);

#endif /* GRPH_NS_STDIO_H */

