//
//  strutils.h
//  GRPH stdlib - libgrph
//
//  Autogenerated by `grph gen-header strutils`.
//
//  This Source Code Form is subject to the terms of the Mozilla Public
//  License, v. 2.0. If a copy of the MPL was not distributed with this
//  file, You can obtain one at https://mozilla.org/MPL/2.0/.
//

#ifndef GRPH_NS_STRUTILS_H
#define GRPH_NS_STRUTILS_H

#include "grph_types.h"
#include "grph_shapes.h"

grph_integer_t grph_strutils_getStringLength(grph_string_t string);
grph_string_t grph_strutils_substring(grph_string_t string, grph_integer_t start, optional_integer_t end);
grph_integer_t grph_strutils_indexInString(grph_string_t string, grph_string_t substring);
grph_integer_t grph_strutils_lastIndexInString(grph_string_t string, grph_string_t substring);
grph_boolean_t grph_strutils_stringContains(grph_string_t string, grph_string_t substring);
grph_integer_t grph_strutils_charToInteger(grph_string_t character);
grph_string_t grph_strutils_integerToChar(grph_integer_t codePoint);
grph_string_t grph_strutils_setStringLength(grph_string_t string, grph_integer_t length, optional_string_t fill);

#endif /* GRPH_NS_STRUTILS_H */

